### ISSUE TITLE
Cannot load the llusbdac.ko module

### ISSUE THREAD

**Issue by morgenstern09** [zhangboyang/llusbdac#2]
Hello,

Loading the llusbdac.ko module gives out this error in dmesg: Unknown symbol __dynamic_pr_debug

Do you have any idea what could be wrong? It seems like something kernel related.

Thanks.

**Comment by morgenstern09** [comment]
I think the issue is that I'm trying to use this module on the WM1A/Z kernel.

On the A45 it runs as intended.

If you have a clue about resolving this issue for the WM1A/Z kernel too, it would be awesome.

**Comment by zhangboyang** [comment]
Hello,

I don't have a WM1A or WM1Z, so I'm afraid I can't test it for you. It seems there are some kernel configration differences between NW-ZX300A and NW-WM1A/Z. You mentioned `llusbdac.ko`, did you compiled it yourself, or extracted from released installer? I think you can download NW-WM1A/Z kernel source code from [this link](https://oss.sony.net/Products/Linux/Audio/category01.html#ca3). You need prepare the kernel, as written in `get_kernel.sh`. Take care choosing kernel configration file. I'm using `BBDMP3_linux_debug_defconfig` for my NW-ZX300A, as instructed by `HowToBuild.txt` in sony's source tarball.

Even it compiled successfully, I'm wondering if it can runs on NW-WM1A/Z since my code is tightly connected to NW-ZX300A. Anyway, good luck and happy hacking :)

**Comment by morgenstern09** [comment]
> Hello,
> 
> I don't have a WM1A or WM1Z, so I'm afraid I can't test it for you. It seems there are some kernel configration differences between NW-ZX300A and NW-WM1A/Z. You mentioned `llusbdac.ko`, did you compiled it yourself, or extracted from released installer? I think you can download NW-WM1A/Z kernel source code from [this link](https://oss.sony.net/Products/Linux/Audio/category01.html#ca3). You need prepare the kernel, as written in `get_kernel.sh`. Take care choosing kernel configration file. I'm using `BBDMP3_linux_debug_defconfig` for my NW-ZX300A, as instructed by `HowToBuild.txt` in sony's source tarball.
> 
> Even it compiled successfully, I'm wondering if it can runs on NW-WM1A/Z since my code is tightly connected to NW-ZX300A. Anyway, good luck and happy hacking :)

Thanks for the reply!

I used the module included in the installer. I'll have a go at compiling it myself using the WM1A/Z kernel in a Linux virtual machine I use.

I don't compile stuff usually, but I checked the "get_kernel.sh" and I noticed that it shouldn't be something difficult to do.

A45 also runs BBDMP3_linux, while A55 runs BBDMP5_linux, and WM1A/Z runs BBDMP2_linux.

**Comment by morgenstern09** [comment]
Ok, I compiled the llusbdac.ko module using the WM1A/Z kernel (with its BBDMP2_linux defconfig) and it works fine!

Thank you for your work!

![image](https://user-images.githubusercontent.com/31675407/162273772-66f81d82-d452-497c-b951-e177a5baee48.png)

**Comment by zhangboyang** [comment]
Wow, that's cool. Thanks for this information.

**Comment by morgenstern09** [comment]
It also works on the A55 after compiling the module with the A55 kernel (BBDMP5_linux_debug).

**Comment by zhangboyang** [comment]
@morgenstern09
That's great, thanks for testing :smiley:

**Comment by Bradengar** [comment]
> It also works on the A55 after compiling the module with the A55 kernel (BBDMP5_linux_debug).

Hi. Can you please share the compiled installer? I can't find it anywhere and have no skills to compile it myself
